### ISSUE TITLE
Fix ANR error

### ISSUE THREAD

**Issue by orzechowskikamil** [orzechowskikamil/motoresponder#204]
https://play.google.com/apps/publish/?hl=pl&dev_acc=15274614972019768519#ErrorClusterDetailsPlace:p=com.medziku.motoresponder&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.NullPointerException&tf=PhoneNumbersComparator.java&tc=com.medziku.motoresponder.logic.PhoneNumbersComparator&tm=normalizeNumber&nid&an&c&s=new_status_desc&ed=0

**Comment by orzechowskikamil** [comment]
java.lang.RuntimeException: An error occured while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:304)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
    at com.medziku.motoresponder.logic.PhoneNumbersComparator.normalizeNumber(PhoneNumbersComparator.java:53)
    at com.medziku.motoresponder.logic.PhoneNumbersComparator.isNumberNormal(PhoneNumbersComparator.java:73)
    at com.medziku.motoresponder.logic.NumberRules.isNumberNormal(NumberRules.java:59)
    at com.medziku.motoresponder.logic.NumberRules.numberRulesAllowResponding(NumberRules.java:24)
    at com.medziku.motoresponder.logic.RespondingDecision.shouldRespond(RespondingDecision.java:43)
    at com.medziku.motoresponder.logic.RespondingTask.handleRespondingTask(RespondingTask.java:130)
    at com.medziku.motoresponder.logic.RespondingTask.doInBackground(RespondingTask.java:50)
    at com.medziku.motoresponder.logic.RespondingTask.doInBackground(RespondingTask.java:12)
    at android.os.AsyncTask$2.call(AsyncTask.java:292)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    ... 4 more
